name: github_commit_notifier
publish_to: none
description: Creates a desktop notification on commits to github repositories.
version: 1.0.0
homepage: https://github.com/zanderso/github_commit_notifier

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  desktop_notifications: any
  github: any
  path: any
  pedantic: any
